#!/usr/bin/ash

# Starchy
# Copyright (C) 2025 LightDig

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# SOFTWARE.

run_hook() {
	i=3
	while true; do
		printf "Please enter boot password"
		[[ $i -eq 3 ]] && printf " (leave blank to shut down)"
		echo ":"
		read -s passwd
		[[ -z $passwd ]] && poweroff -f
		if [[ "$(echo $passwd | sha512sum)" = "PASSWD_HASH  -" ]]; then
			break
			echo "Password okay - booting..."
		else
			i=$(($i-1))
			sleep 2
			echo "Incorrect password, try again"
			echo
			if [[ $i -eq 0 ]]; then
				echo "Couldn't boot system"
				echo "Shutting down..."
				sleep 3
				poweroff -f
			fi
		fi
	done
}
