#!/usr/bin/ash

run_hook() {
	i=3
	while true; do
		printf "Please enter boot password"
		[[ $i -eq 3 ]] && printf " (leave blank to shut down)"
		echo ":"
		read -s passwd
		[[ -z $passwd ]] && poweroff -f
		if [[ "$(echo $passwd | sha512sum)" = "PASSWD_HASH  -" ]]; then
			break
			echo "Password okay - booting..."
		else
			i=$(($i-1))
			sleep 2
			echo "Incorrect password, try again"
			echo
			if [[ $i -eq 0 ]]; then
				echo "Couldn't boot system"
				echo "Shutting down..."
				sleep 3
				poweroff -f
			fi
		fi
	done
}
